version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    working_directory: /tmp
    steps:
      - checkout
      - run:
          command: ./gradlew build


      - run:
          name: Creating Artifacts
          command:
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artficats-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
